BEGIN;

-- Insert data into the 'cover' table
INSERT INTO "cover" ("name", "url") VALUES 
('realite', 'https://storage.googleapis.com/bucket_antcritique/Films/covers/Realite_Cover.jpg'),
('babylon', 'https://storage.googleapis.com/bucket_antcritique/Films/covers/Babylon.jpg'),
('friends', 'https://storage.googleapis.com/bucket_antcritique/Films/covers/Friends.jpg'),
('dragon-quest', 'https://storage.googleapis.com/bucket_antcritique/Films/covers/Dragon_Quest.jpg'),
('la-horde-du-contrevent', 'https://storage.googleapis.com/bucket_antcritique/Films/covers/Horde_Contrevent_Accueil.jpg')
;


-- Insert data into the 'movie' table
INSERT INTO "movie" ("title", "poster_url", "director", "actors", "genre", "resume", "allocine_link", "senscritique_link", "rate", "critic", "year", "isAllTimeFavorite")
VALUES
('Shutter Island', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Shutter_Island.jpg', 'Martin Scorsese', 'Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley...', 'Thriller', 'En 1954, une des patientes de l’hôpital psychiatrique situé sur l’île de Shutter Island, au large de Boston, a disparu sans laisser de traces. Le marshal Teddy Daniels et son coéquipier Chuck Aule, sont envoyés sur place pour mener l’enquête. L’affaire se révèle vite très mystérieuse pour les deux hommes.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=132039.html', 'https://www.senscritique.com/film/shutter_island/405140', 10, 'Mon film préféré, tout simplement.', 2010, true),
('Réalité', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Realite.jpg', 'Quentin Dupieux', 'Alain Chabat, Jonathan Lambert...', 'Comédie, SF', 'Jason veut réaliser un film d’horreur, son producteur le finance à la seule condition qu’il trouve le meilleur gémissement de l’histoire du cinéma en 48h.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=204027.html', 'https://www.senscritique.com/film/realite/8193990', 10, 'Ovni total. Le film joue sur les dimensions et se balade et nous perd entre un film, un rêve et la réalité. Les personnages se croisent et intéragissent entre les différentes dimensions. Le climax est phénoménal et m’a laissé sur les fesses. On est complètement perdus mais c’est renversant. Et bien sur Alain Chabat est génial, mais c’est un pléonasme. Coup de coeur absolu.', 2014, true),
('Old Boy', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Old_Boy.jpg', 'Park Chan-Wook', 'Choi Min-Sik, Yoo Ji-Tae, Kang Hye-Jung, Kim Byung-Ok...', 'Thriller, Suspense', 'Après avoir été enlevé et emprisonné durant 15 ans, sans savoir pourquoi, Oh Dae-Su est libéré et recherche les raisons de son enfermement.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=54137.html', 'https://www.senscritique.com/film/old_boy/444625', 10, 'Enorme claque.', 2008, true),
('Interstellar', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Interstellar.jpg', 'Christopher Nolan', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain...', 'SF', 'Alors que la vie sur Terre touche à sa fin, un groupe d’explorateurs s’attelle à la mission la plus importante de l’histoire de l’humanité : franchir les limites de notre galaxie pour savoir si l’homme peut vivre sur une autre planète...', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=114782.html', 'https://www.senscritique.com/film/interstellar/388583', 10, 'Mon film de science-fiction favori. Les images sont bluffantes, le scénario est une perle d’intelligence. Et que dire du thème principal d’Hans Zimmer, qui vous marque à jamais. Somptueux. ', 2014, true),
('Le Roi Lion', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Roi_Lion.jpg', 'Roger Allers, Rob Minkoff', 'Emmanuel Curtil, Matthew Broderick, Dimitri Rougeul...', 'Animation', 'Dans la savane africaine, Simba, le fils du roi lion Mufasa, vient de naître et il est présenté à tous les animaux sur lesquels il est appelé à régner un jour. Mais si la liesse s’empare de la plupart des animaux, Scar, le frère de Mufasa, qui voit une fois de plus le trône lui échapper, rumine dans l’ombre et prépare sa vengeance.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=10862.html', 'https://www.senscritique.com/film/le_roi_lion/493747', 10, '', 1993, true),
('Le Seigneur des Anneaux - Le retour du Roi', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Retour_Du_Roi.jpg', 'Peter Jackson', 'Elijah Wood, Sean Astin, Viggo Mortensen, Ian McKellen...', 'Aventure, Fantasy', 'La bataille pour la Terre du Milieu a commencé. Frodon et Sam, guidés par Gollum, poursuivent leur mission à travers les terres du Mordor pour détruire l’Anneau Unique. Tandis que le pouvoir de Sauron grandit, Aragorn, l’héritier du trône du Gondor, rassemble l’armée des Hommes contre les forces du Mal, afin de laisser une chance au porteur de l’Anneau d’accomplir sa quête.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=39187.html', 'https://www.senscritique.com/film/le_seigneur_des_anneaux_le_retour_du_roi/481351', 9, '', 2003, true),
('Match Point', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Match_Point.jpg', 'Woody Allen', 'Jonathan Rhys-Meyers, Scarlett Johansson, Emily Mortimer...', 'Comédie Dramatique', 'Jeune professeur de tennis issu d’un milieu modeste, Chris Wilton se fait embaucher dans un club huppé des beaux quartiers de Londres. Il se lie d’amitié avec Tom Hewett, fils de bonne famille. Celui-ci l’invite un jour dans la maison de campagne de ses parents. Chris séduit alors Chloe, la sœur de Tom. Il veut l’épouser. Mais un jour, il rencontre Nola Rice, la fiancée de Tom, une jeune actrice américaine en quête de travail...', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=57866.html', 'https://www.senscritique.com/film/match_point/430076', 9, '', 2010, true),
('Astérix & Obélix - Mission Cléopatre', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Asterix.jpg', 'Alain Chabat', 'Gérard Depardieu, Christian Clavier, Jamel Debbouze...', 'Comédie', 'A Alexandrie, en 52 av. J.-C., Cléopâtre, désireuse de prouver la supériorité du peuple égyptien, relève le défi lancé par l’Empereur romain Jules César : construire un palais en trois mois ! Pour ce faire, Cléopâtre fait appel à l’architecte Numérobis. S’il réussit, elle le couvrira d’or. S’il échoue, elle le jettera aux crocodiles. Celui-ci, conscient du défi à relever, cherche de l’aide auprès de son vieil ami Panoramix. Le druide fait le voyage en Égypte avec Astérix et Obélix. De son côté, Amonbofis, l’architecte officiel de Cléopâtre, jaloux que la reine ait choisi Numérobis pour construire le palais, va tout mettre en œuvre pour faire échouer son concurrent.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=28537.html', 'https://www.senscritique.com/film/asterix_obelix_mission_cleopatre/411737', 9, 'A mourir de rire. L’impact est surement d’autant plus grand que je l’ai vu jeune. Mais à mon sens aucun film depuis n’a été aussi drôle.', 2002, true)
;

-- Insert data into the 'tv_show' table
INSERT INTO "tv_show" ("title", "poster_url", "creator", "actors", "genre", "resume", "allocine_link", "senscritique_link", "rate", "critic", "rank")
VALUES
('Breaking Bad', 'https://storage.googleapis.com/bucket_antcritique/Films/tv-shows/Breaking_Bad.jpg', 'Vince Gilligan', 'Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris...', 'Thriller, Drame', 'Walter White, 50 ans, est professeur de chimie dans un lycée du Nouveau-Mexique. Pour subvenir aux besoins de Skyler, sa femme enceinte, et de Walt Junior, son fils handicapé, il est obligé de travailler doublement. Son quotidien déjà morose devient carrément noir lorsqu''il apprend qu''il est atteint d''un incurable cancer des poumons. Les médecins ne lui donnent pas plus de deux ans à vivre. Pour réunir rapidement beaucoup d''argent afin de mettre sa famille à l''abri, Walter ne voit plus qu''une solution : mettre ses connaissances en chimie à profit pour fabriquer et vendre de la méthamphétamine. Il propose à Jesse, un de ses anciens élèves devenu un petit dealer de seconde zone, de faire équipe avec lui.', 'https://www.allocine.fr/series/ficheserie_gen_cserie=3517.html', 'https://www.senscritique.com/serie/breaking_bad/264963', 10, 'Meilleure série jamais écrite. Une montée en puissance durant les saisons. Des moments de tension folles, des twists et des scènes marquantes, et une fin de série qui restera dans les annales.', 1),
('Friends', 'https://storage.googleapis.com/bucket_antcritique/Films/tv-shows/Friends.jpg', 'David Crane & Marta Kauffmann', 'Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc, Matthew Perry et David Schwimmer', 'Comédie, Romance', 'Les péripéties de six jeunes new-yorkais liés par une profonde amitié. Entre amour, travail et famille, ils partagent leurs bonheurs et leurs soucis..', 'https://www.allocine.fr/series/ficheserie_gen_cserie=49.html', 'https://www.senscritique.com/serie/friends/484823', 10, 'La sitcom absolue.', 2),
('Lost - Les disparus', 'https://storage.googleapis.com/bucket_antcritique/Films/tv-shows/Lost.jpg', 'Damon Lindelof & J.J. Abrahams', 'Matthew Fox, Terry O''Quinn, Evangeline Lilly, Jorge Garcia...', 'Aventure, Drame, SF', 'Après le crash de leur avion sur une île perdue de l’océan Pacifique, les survivants, livrés à eux-mêmes, doivent apprendre à cohabiter et survivre dans cet environnement hostile. Bien vite, ils se rendent compte qu''une menace semble planer sur l''île...', 'https://www.allocine.fr/series/ficheserie_gen_cserie=223.html', 'https://www.senscritique.com/serie/lost_les_disparus/74966', 10, 'La série qui m''aura le plus marqué ma jeunesse.', 3),
('Game of Thrones', 'https://storage.googleapis.com/bucket_antcritique/Films/tv-shows/Game_Of_Thrones.jpg', 'David Benioff & D.B. Weiss', 'Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington...', 'Fantasy, Drame, Aventure', 'Sur le continent de Westeros en proie au retour de l''Hiver, les grands Seigneurs et la fille du roi déchu se disputent le Trône de Fer.', 'https://www.allocine.fr/series/ficheserie_gen_cserie=7157.html', 'https://www.senscritique.com/serie/game_of_thrones/225391', 9, 'Série qui à marqué son époque et la pop-culture.', 4),
('Black Mirror', 'https://storage.googleapis.com/bucket_antcritique/Films/tv-shows/Black_Mirror.png', 'Charlie Brooker', 'Rory Kinnear, Anna Wilson-Jones, Lindsay Duncan...', 'SF, Thriller', 'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran et les conséquences de cette dépendance.', 'https://www.allocine.fr/series/ficheserie_gen_cserie=10855.html', 'https://www.senscritique.com/serie/black_mirror/438579', 9, 'Terrifiant.', 5)
;

-- Insert data into the 'book' table
INSERT INTO "book" ("title", "cover_url", "author", "genre", "resume", "babelio_link", "senscritique_link", "rate", "critic", "rank")
VALUES
('Le joueur d''échecs', 'https://storage.googleapis.com/bucket_antcritique/Films/books/Joueur_Echec.jpg', 'Stefan Zweig', 'Nouvelle', 'Qui est cet inconnu capable d''en remontrer au grand Czentovic, le champion mondial des échecs, véritable prodige aussi fruste qu''antipathique ? Peut-on croire, comme il l''affirme, qu''il n''a pas joué depuis plus de vingt ans ? Voilà un mystère que les passagers oisifs de ce paquebot de luxe aimeraient bien percer. Le narrateur y parviendra. Les circonstances dans lesquelles l''inconnu a acquis cette science sont terribles. Elles nous reportent aux expérimentations nazies sur les effets de l''isolement absolu, lorsque, aux frontières de la folie, entre deux interrogatoires, le cerveau humain parvient à déployer ses facultés les plus étranges. Une fable inquiétante, fantastique, qui, comme le dit le personnage avec une ironie douloureuse, « pourrait servir d''illustration à la charmante époque où nous vivons ».', 'https://www.babelio.com/livres/Zweig-Le-Joueur-dechecs/1771', 'https://www.senscritique.com/livre/le_joueur_d_echecs/130709', 10, 'Une plongée dans la psyché et la folie, racontée sous l''angle d''un affrontement entre deux joueurs d''échecs. La nouvelle est courte et se lit en quelques heures, mais est absolument boulversante', 1),
('Gagner la guerre', 'https://storage.googleapis.com/bucket_antcritique/Films/books/Gagner_Guerre.jpg', 'Jean-Philippe Jaworski', 'Fantasy', 'Don Benvenuto est au service du Podestat de la République mais est toujours très habile pour se fourrer dans les pires situations qui soient.', 'https://www.babelio.com/livres/Jaworski-Gagner-la-guerre/117385', 'https://www.senscritique.com/livre/gagner_la_guerre/148702', 10, 'Le roman est issue du recueil de nouvelles Janua Vera du même auteur. Tout simplement l''aventure Fantasy la plus passionnante et bien écrite que j''ai eu l''occasion de lire. Un bijou', 2),
('La Horde du Contrevent', 'https://storage.googleapis.com/bucket_antcritique/Films/books/Horde.jpg', 'Alain Damasio', 'Fantasy', '« Imaginez une Terre poncée, avec en son centre une bande de cinq mille kilomètres de large et sur ses franges un miroir de glace à peine rayable, inhabité. Imaginez qu’un vent féroce en rince la surface. Que les villages qui s’y sont accrochés, avec leurs maisons en goutte d’eau, les chars à voile qui la strient, les airpailleurs debout en plein flot, tous résistent. Imaginez qu’en Extrême-Aval ait été formé un bloc d’élite d’une vingtaine d’enfants aptes à remonter au cran, rafale en gueule, leur vie durant, le vent jusqu’à sa source, à ce jour jamais atteinte : l’Extrême-Amont. Mon nom est Sov Strochnis, scribe. Mon nom est Caracole le troubadour et Oroshi Melicerte, aéromaître. Je m’appelle aussi Golgoth, traceur de la Horde, Arval l’éclaireur et parfois même Larco lorsque je braconne l’azur à la cage volante. Ensemble, nous formons la Horde du Contrevent. Il en a existé trente-trois en huit siècles, toutes infructueuses. Je vous parle au nom de la trente-quatrième : sans doute l’ultime. ».', 'https://www.babelio.com/livres/Damasio-La-Horde-du-Contrevent/542', 'https://www.senscritique.com/film/old_boy/444625', 10, 'Icone du roman de science-fiction, une lecture rude mais dont on ne ressort pas indemme.', 3),
('Les fourmis', 'https://storage.googleapis.com/bucket_antcritique/Films/books/Les_Fourmis.jpg', 'Bernard Werber', 'Roman, SF', 'Lorsqu''il entre dans la cave de la maison léguée par un oncle entomologiste, Jonathan Wells est loin de se douter qu''il va à la rencontre des fourmis.', 'https://www.babelio.com/livres/Werber-Les-Fourmis/4365', 'https://www.senscritique.com/livre/les_fourmis/411948', 9, NULL, 4),
('L''Assassin Royal', 'https://storage.googleapis.com/bucket_antcritique/Films/books/Assassin_Royal.jpg', 'Robin Hobb', 'Fantasy', 'Bâtard du prince chevalerie, le jeune Fitz grandit dans l''ombre de la forteresse de Castelcerf, où le roi subtil ambitionne de faire de lui son assassin personnel. Mais pour survivre, et avant même d''apprendre à manier la lame, il lui faudra faire preuve d''une connaissance parfaite des arcanes de la politique.', 'https://www.babelio.com/livres/Hobb-Lassassin-royal-tome-1--Lapprenti-assassin/6863', 'https://www.senscritique.com/livre/l_assassin_royal/13259629', 9, NULL, 5)
;

-- Insert data into the 'video_game' table
INSERT INTO "video_game" ("title", "cover_url", "editor", "genre", "resume", "jvcom_link", "senscritique_link", "rate", "critic")
VALUES
('Dragon Quest', 'https://storage.googleapis.com/bucket_antcritique/Films/games/Dragon_Quest.jpg', 'Square Enix', 'RPG', 'Huitième épisode de la saga de Yuji Horii, Dragon Quest : L''Odyssée du Roi Maudit vous entraîne en quête d''un remède pour le roi Trode, changé en crapaud par le vil bouffon Dhoulmagus après avoir entravé ses plans. Accompagné d''un mystérieux mais courageux garçon dont on ne sait rien, d''un voleur balafré et de bien d''autres compagnons, nos héros vont devoir lever la malédiction et sauver leur royaume, figé dans la pierre.', 'https://www.jeuxvideo.com/jeux/playstation-2-ps2/00011324-dragon-quest-l-odyssee-du-roi-maudit.htm', 'https://www.senscritique.com/jeuvideo/dragon_quest_viii_l_odyssee_du_roi_maudit/18055583', 10, 'Une aventure onirique et exceptionnelle.'),
('Pokemon Or', 'https://storage.googleapis.com/bucket_antcritique/Films/games/Pokemon.png', 'Game Freak', 'RPG', 'Pokémon Version Or est un jeu de rôle sorti sur Gameboy. Dirigez un dresseur de Pokémons qui doit devenir le meilleur d''entre tous. Pour cela, capturez des créatures et faites-les évoluer pour qu''elles deviennent de plus en plus fortes afin de battre la ligue Pokémon.', 'https://www.jeuxvideo.com/jeux/jeu-57991', 'https://www.senscritique.com/jeuvideo/pokemon_or/109466', 9, NULL),
('The Witcher 3', 'https://storage.googleapis.com/bucket_antcritique/Films/games/Witcher.jpg', 'CD Projekt', 'Action/RPG', 'The Witcher 3 est un RPG en monde ouvert, dans un univers Fantasy hautement scénarisé où vos choix sont décisifs. Vous incarnez un tueur de monstres professionnel chargé de retrouver l''enfant de la prophétie dans un vaste monde riche en cités marchandes, cols périlleux et grottes oubliées.', 'https://www.jeuxvideo.com/jeux/jeu-77555/', 'https://www.senscritique.com/serie/lost_les_disparus/74966', 9, 'Gros morceau.'),
('The Last of Us - Part Two', 'https://storage.googleapis.com/bucket_antcritique/Films/games/Last_Of_Us.png', 'Naughty Dog', 'Action, Aventure, Survival-Horror', 'Cinq ans après les événements du premier opus, Ellie et Joel s’installent dans le Wyoming. La vie en communauté leur apporte une certaine stabilité, malgré la menace que représentent les infectés. Quand un violent incident vient troubler cette paix, Ellie entame une implacable quête de justice.', 'https://www.jeuxvideo.com/jeux/ps4/jeu-412345/', 'https://www.senscritique.com/jeuvideo/the_last_of_us_part_ii/12766010', 9, 'Quelle claque, on en ressort pas indemme.'),
('Red Dead Redemption', 'https://storage.googleapis.com/bucket_antcritique/Films/games/Red_Dead.jpg', 'Rockstar Games', 'Action', 'L''Amérique, 1911. Le Grand Ouest mythique touche à sa fin. Lorsque des agents fédéraux menacent sa famille, le hors-la-loi John Marston se voit contraint de retrouver ses anciens frères d''armes. Découvrez un combat pour la survie dans l''immensité de l''Ouest américain et du Mexique.', 'https://www.jeuxvideo.com/jeux/jeu-71609/', 'https://www.senscritique.com/jeuvideo/red_dead_redemption/191198', 9, NULL)
;

COMMIT;