BEGIN;

-- Insert data into the 'cover' table
INSERT INTO cover ("name", "url") VALUES 
('Réalité', 'https://storage.googleapis.com/bucket_antcritique/Films/covers/Realite_Cover.jpg'),
('Babylon', 'https://storage.googleapis.com/bucket_antcritique/Films/covers/Babylon.jpg')
;


-- Insert data into the 'movie' table
INSERT INTO movie ("title", "poster_url", "director", "actors", "genre", "resume", "allocine_link", "senscritique_link", "rate", "critic", "year", "isAllTimeFavorite")
VALUES
('Shutter Island', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Shutter_Island.jpg', 'Martin Scorsese', 'Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley...', 'Thriller', 'En 1954, une des patientes de l’hôpital psychiatrique situé sur l’île de Shutter Island, au large de Boston, a disparu sans laisser de traces. Le marshal Teddy Daniels et son coéquipier Chuck Aule, sont envoyés sur place pour mener l’enquête. L’affaire se révèle vite très mystérieuse pour les deux hommes.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=132039.html', 'https://www.senscritique.com/film/shutter_island/405140', 10, 'Mon film préféré, tout simplement.', 2010, true),
('Réalité', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Realite.jpg', 'Quentin Dupieux', 'Alain Chabat, Jonathan Lambert...', 'Comédie, SF', 'Jason veut réaliser un film d’horreur, son producteur le finance à la seule condition qu’il trouve le meilleur gémissement de l’histoire du cinéma en 48h.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=204027.html', 'https://www.senscritique.com/film/realite/8193990', 10, 'Ovni total. Le film joue sur les dimensions et se balade et nous perd entre un film, un rêve et la réalité. Les personnages se croisent et intéragissent entre les différentes dimensions. Le climax est phénoménal et m’a laissé sur les fesses. On est complètement perdus mais c’est renversant. Et bien sur Alain Chabat est génial, mais c’est un pléonasme. Coup de coeur absolu.', 2014, true),
('Old Boy', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Old_Boy.jpg', 'Park Chan-Wook', 'Choi Min-Sik, Yoo Ji-Tae, Kang Hye-Jung, Kim Byung-Ok...', 'Thriller, Suspense', 'Après avoir été enlevé et emprisonné durant 15 ans, sans savoir pourquoi, Oh Dae-Su est libéré et recherche les raisons de son enfermement.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=54137.html', 'https://www.senscritique.com/film/old_boy/444625', 10, 'Enorme claque.', 2008, true),
('Interstellar', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Interstellar.jpg', 'Christopher Nolan', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain...', 'SF', 'Alors que la vie sur Terre touche à sa fin, un groupe d’explorateurs s’attelle à la mission la plus importante de l’histoire de l’humanité : franchir les limites de notre galaxie pour savoir si l’homme peut vivre sur une autre planète...', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=114782.html', 'https://www.senscritique.com/film/interstellar/388583', 10, 'Mon film de science-fiction favori. Les images sont bluffantes, le scénario est une perle d’intelligence. Et que dire du thème principal d’Hans Zimmer, qui vous marque à jamais. Somptueux. ', 2014, true),
('Le Roi Lion', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Roi_Lion.jpg', 'Roger Allers, Rob Minkoff', 'Emmanuel Curtil, Matthew Broderick, Dimitri Rougeul...', 'Animation', 'Dans la savane africaine, Simba, le fils du roi lion Mufasa, vient de naître et il est présenté à tous les animaux sur lesquels il est appelé à régner un jour. Mais si la liesse s’empare de la plupart des animaux, Scar, le frère de Mufasa, qui voit une fois de plus le trône lui échapper, rumine dans l’ombre et prépare sa vengeance.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=10862.html', 'https://www.senscritique.com/film/le_roi_lion/493747', 10, '', 1993, true),
('Le Seigneur des Anneaux - Le retour du Roi', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Retour_Du_Roi.jpg', 'Peter Jackson', 'Elijah Wood, Sean Astin, Viggo Mortensen, Ian McKellen...', 'Aventure, Fantasy', 'La bataille pour la Terre du Milieu a commencé. Frodon et Sam, guidés par Gollum, poursuivent leur mission à travers les terres du Mordor pour détruire l’Anneau Unique. Tandis que le pouvoir de Sauron grandit, Aragorn, l’héritier du trône du Gondor, rassemble l’armée des Hommes contre les forces du Mal, afin de laisser une chance au porteur de l’Anneau d’accomplir sa quête.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=39187.html', 'https://www.senscritique.com/film/le_seigneur_des_anneaux_le_retour_du_roi/481351', 9, '', 2003, true),
('Match Point', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Match_Point.jpg', 'Woody Allen', 'Jonathan Rhys-Meyers, Scarlett Johansson, Emily Mortimer...', 'Comédie Dramatique', 'Jeune professeur de tennis issu d’un milieu modeste, Chris Wilton se fait embaucher dans un club huppé des beaux quartiers de Londres. Il se lie d’amitié avec Tom Hewett, fils de bonne famille. Celui-ci l’invite un jour dans la maison de campagne de ses parents. Chris séduit alors Chloe, la sœur de Tom. Il veut l’épouser. Mais un jour, il rencontre Nola Rice, la fiancée de Tom, une jeune actrice américaine en quête de travail...', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=57866.html', 'https://www.senscritique.com/film/match_point/430076', 9, '', 2010, true),
('Astérix & Obélix - Mission Cléopatre', 'https://storage.googleapis.com/bucket_antcritique/Films/movies/Asterix.jpg', 'Alain Chabat', 'Gérard Depardieu, Christian Clavier, Jamel Debbouze...', 'Comédie', 'A Alexandrie, en 52 av. J.-C., Cléopâtre, désireuse de prouver la supériorité du peuple égyptien, relève le défi lancé par l’Empereur romain Jules César : construire un palais en trois mois ! Pour ce faire, Cléopâtre fait appel à l’architecte Numérobis. S’il réussit, elle le couvrira d’or. S’il échoue, elle le jettera aux crocodiles. Celui-ci, conscient du défi à relever, cherche de l’aide auprès de son vieil ami Panoramix. Le druide fait le voyage en Égypte avec Astérix et Obélix. De son côté, Amonbofis, l’architecte officiel de Cléopâtre, jaloux que la reine ait choisi Numérobis pour construire le palais, va tout mettre en œuvre pour faire échouer son concurrent.', 'https://www.allocine.fr/film/fichefilm_gen_cfilm=28537.html', 'https://www.senscritique.com/film/asterix_obelix_mission_cleopatre/411737', 9, 'A mourir de rire. L’impact est surement d’autant plus grand que je l’ai vu jeune. Mais à mon sens aucun film depuis n’a été aussi drôle.', 2002, true)
;

COMMIT;